#!/usr/bin/env bash
#
# SeaZero Setup — First-time Agent Zero configuration
#
# Prerequisites: SeaClaw built + Docker installed
# Usage: bash seazero/scripts/setup.sh
#

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

info()  { echo -e "${CYAN}  ▸${RESET} $*"; }
ok()    { echo -e "${GREEN}  ✓${RESET} $*"; }
warn()  { echo -e "${YELLOW}  ⚠${RESET} $*"; }
err()   { echo -e "${RED}  ✗${RESET} $*" >&2; }
die()   { err "$*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEAZERO_DIR="$(dirname "$SCRIPT_DIR")"
SEACLAW_DIR="$(dirname "$SEAZERO_DIR")"

echo ""
echo -e "${BOLD}${CYAN}  SeaZero Setup${RESET}"
echo -e "  ${DIM}Agent Zero integration for SeaClaw${RESET}"
echo ""

# ── Check prerequisites ──────────────────────────────────────

info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    die "Docker is required. Install: https://docs.docker.com/get-docker/"
fi
ok "Docker found: $(docker --version | head -1)"

if ! docker compose version &>/dev/null && ! command -v docker-compose &>/dev/null; then
    die "Docker Compose is required."
fi
ok "Docker Compose available"

if [ ! -f "$SEACLAW_DIR/dist/sea_claw" ] && ! command -v sea_claw &>/dev/null; then
    warn "SeaClaw binary not found. Build it first: make release"
fi

# ── Check if Agent Zero image exists ─────────────────────────

info "Checking Agent Zero Docker image..."

if docker image inspect seazero/agent-zero:latest &>/dev/null; then
    ok "Image seazero/agent-zero:latest found"
else
    warn "Image not found. Building from Dockerfile..."
    if [ -f "$SEAZERO_DIR/Dockerfile.agent-zero" ]; then
        docker build -t seazero/agent-zero:latest -f "$SEAZERO_DIR/Dockerfile.agent-zero" "$SEAZERO_DIR"
        ok "Image built"
    else
        warn "No Dockerfile.agent-zero yet — will be created in Phase 1"
        info "For now, you can pull the upstream Agent Zero image:"
        echo -e "    ${CYAN}docker pull frdel/agent-zero:latest${RESET}"
    fi
fi

# ── Create config directory ──────────────────────────────────

SEAZERO_HOME="${HOME}/.seazero"
mkdir -p "$SEAZERO_HOME"/{agents,logs,memory}
ok "Data directory: $SEAZERO_HOME"

# ── Write environment file ───────────────────────────────────

ENV_FILE="$SEAZERO_DIR/config/agent-zero.env"

if [ -f "$ENV_FILE" ]; then
    info "Environment file exists: $ENV_FILE"
else
    # Try to read LLM config from SeaClaw's config
    SEACLAW_CONFIG="${HOME}/.config/seaclaw/config.json"
    LLM_PROVIDER=""
    LLM_API_KEY=""
    LLM_MODEL=""

    if [ -f "$SEACLAW_CONFIG" ]; then
        info "Reading LLM config from SeaClaw..."
        # Simple grep-based extraction (no jq dependency)
        LLM_PROVIDER=$(grep -o '"llm_provider"[[:space:]]*:[[:space:]]*"[^"]*"' "$SEACLAW_CONFIG" | head -1 | sed 's/.*: *"//;s/"//')
        LLM_API_KEY=$(grep -o '"llm_api_key"[[:space:]]*:[[:space:]]*"[^"]*"' "$SEACLAW_CONFIG" | head -1 | sed 's/.*: *"//;s/"//')
        LLM_MODEL=$(grep -o '"llm_model"[[:space:]]*:[[:space:]]*"[^"]*"' "$SEACLAW_CONFIG" | head -1 | sed 's/.*: *"//;s/"//')
        ok "Found: $LLM_PROVIDER / $LLM_MODEL"
    fi

    cat > "$ENV_FILE" << EOF
# SeaZero Agent Zero Environment
# Auto-generated by setup.sh — edit as needed
#
# LLM Configuration (shared with SeaClaw)
LLM_PROVIDER=${LLM_PROVIDER:-openrouter}
LLM_MODEL=${LLM_MODEL:-moonshotai/kimi-k2.5}
LLM_API_KEY=${LLM_API_KEY:-}
LLM_API_URL=

# Agent Configuration
AGENT_PORT=8080
LOG_LEVEL=info
EOF
    ok "Environment written: $ENV_FILE"
fi

# ── Start Agent Zero ─────────────────────────────────────────

echo ""
echo -e "${BOLD}  Ready to start Agent Zero?${RESET}"
echo -e "  ${DIM}This will start a Docker container on localhost:8080${RESET}"
echo ""
read -rp "  Start now? [Y/n]: " yn
yn="${yn:-y}"

if [[ "${yn,,}" == "y" || "${yn,,}" == "yes" ]]; then
    cd "$SEAZERO_DIR"
    if docker compose up -d 2>/dev/null || docker-compose up -d 2>/dev/null; then
        ok "Agent Zero started on localhost:8080"
    else
        warn "Could not start — check docker-compose.yml"
    fi
else
    info "Skipped. Start later with: cd seazero && docker compose up -d"
fi

# ── Summary ──────────────────────────────────────────────────

echo ""
echo -e "${GREEN}  ✓ SeaZero setup complete${RESET}"
echo ""
echo -e "  ${BOLD}Agent Zero:${RESET}  localhost:8080"
echo -e "  ${BOLD}Data:${RESET}        $SEAZERO_HOME"
echo -e "  ${BOLD}Config:${RESET}      $ENV_FILE"
echo ""
echo -e "  ${DIM}Use from SeaClaw:${RESET}"
echo -e "    ${CYAN}sea_claw --config ~/.config/seaclaw/config.json${RESET}"
echo -e "    ${DIM}Then ask: \"Use Agent Zero to ...\"${RESET}"
echo ""
